### PR TITLE
Oscar metadata integration

### PR DESCRIPTION
**Pull request by JerryHamm**
### **Summary**

closing issue #145

- Made updates and changes to SURFACE station creation options
- Fixed an installation issue caused by outdated versions of Celery and NumPy.
- Made changes to how Station metadata is displayed.

### CODE REVIEW

**Review by fabiosato — APPROVED** [review]
looks good to me, is it ready for merging or do you have pending changes to submit?

**Comment by JerryHamm** [comment]
> looks good to me, is it ready for merging or do you have pending changes to submit?

I have a few changes left to apply...should be ready by this evening

**Comment by fabiosato** [comment]
@JerryHamm are you happy to merge these changes into main?

**Comment by JerryHamm** [comment]
> @JerryHamm are you happy to merge these changes into main?

Yes sir, I am 👍🏿

**Pull request merged**
