### PR TITLE
Side bar design

### PR DESCRIPTION
**Pull request by JerryHamm**
Collapsible side bar complete.

### CODE REVIEW

**Comment by isedwards** [comment]
@cla-bot check

**Review by fabiosato — APPROVED** [review]
Approved but I am not able infer from code changes if this will work as expected. Please test in the cloud instance and revert the change if it does not work.

**Comment by fabiosato** [comment]
@JerryHamm can you check and fix this conflict?

**Comment by JerryHamm** [comment]
> @JerryHamm can you check and fix this conflict?

fixed conflicts

**Pull request merged**
